spring:
  application:
    name: habit
  datasource:
    url: jdbc:postgresql://localhost:5432/habittracker
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 5000
app:
  jwt:
    secret: ${JWT_SECRET}

